# Generated by Django 5.0.3 on 2024-04-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=120)),
                ('cantidad', models.IntegerField()),
                ('barrio', models.CharField(max_length=120)),
                ('mes', models.CharField(max_length=120)),
            ],
        ),
    ]
